export const TEXT_ES:{[key: string]: string } = {
  primerTitulo: '¡NOS CASAMOS!',
  tNombres: 'Litzy Michael',
  traduccion: 'Traducir a Inglés',
  pCancion: 'Tu navegador no soporta el elemento de audio.',
  subTitulo: '¡Estás Invitado!',
  mensajeBienvenida1: 'Hay momentos en la vida que se vuelven extraordinarios cuando se comparten con quienes amamos.',
  mensajeBienvenida2: 'Por eso, te invitamos a celebrar con nosotros el inicio de este hermoso viaje.',
  mensajeBienvenida3: 'Tu presencia en el día más importante de nuestras vidas será invaluable para nosotros.',
  soloFaltan: 'Sólo faltan:',
  counterDias: 'Dias',
  counterHoras: 'Horas',
  counterMinutos: 'Minutos',
  counterSeg: 'Segundos',
  // NOMBRE DE PADRES
  tituloInicialPadres: 'Con la bendición de Dios',
  subTituloInicialPadres: 'y nuestros padres',
  nomPadresNovia: 'Padres de la novia',
  nomPadresNovio: 'Padres del novio',
  // FECHA Y BODA
  textFechaBoda: 'Nuestra boda será el sábado:',
  fechaBoda: '31 | Mayo | 2025',
  // GUARDAR LA FECHA
  guardaFecha: 'Guarda la fecha',
  // CEREMONIA Y RECEPCIÓN
  tituloCeremonia: 'CEREMONIA',
  direccionCeremonia: 'Av. Principal la Paloma, San Miguel Tecpán Jilotzingo',
  horaCeremonia: 'Hora: 4:00 P.M.',
  ubicacion: 'VER UBICACIÓN',
  tituloRecepcion: 'RECEPCIÓN',
  direccionRecepcion: 'Convento Santa Clara, Antigua Guatemala',
  horaRecepcion: 'Hora: 7:30 P.M.',
  //ITINERARIO
  tituloItinerario1: 'ITINERARIO',
  subttuloItinerario: 'de boda',
  itiCeremonia: 'Ceremonia Iglesia',
  itiCeremoniaHora: 'Hora: 04:00 P.M.',
  itiCivil: 'Ceremonia Civil',
  itiCivilHora: 'Hora: 04:00 P.M.',
  itiRecepcion: 'Recepción',
  itiRecepcionHora: 'Hora: 03:15 P.M.',
  itiFoto: 'Fotos',
  itiBaileHora: 'Hora: 05:00 P.M.',
  itiComida: 'Fiesta',
  itiComidaHora: 'Hora: 06:45 P.M.',
  itiPastel: 'Pastel',
  itiPastelHora: 'Hora: 07:00 P.M.',
  itiFiesta: 'Fiesta',
  itiFiestaHora: 'Hora: 08:00 P.M.',
  itiDespedida: 'Despedida',
  itiDespedidaHora: 'Hora: 12:00 A.M.',
  // VESTIMENTA O DRESS CODE
  tituloVestimenta: 'VESTIMENTA',
  textoVestimentaUno: 'Estilo Formal',
  textoVestimentaDos: 'Por favor, evita vestir de blanco y sus tonalidades en honor a nuestra celebración.',
  // NUESTROS MOMENTOS
  tituloMomentos: 'Nuestros Momentos',
  textoMomentos: 'Ayuda a que crezcan nuestros recuerdos de este día tan especial. Haz clic en el botón para compartir tus momentos y ser parte de nuestra historia.',
  // REGALOS
  tituloRegalo: 'Regalos',
  textoRegaloUno: 'Tu presencia es nuestro mejor regalo, pero si deseas tener un detalle con nosotros, haz clic aquí para ver las opciones',
  subtituloRegalo: 'Lluvia de sobres',
  textoRegaloDos: 'Los obsequios en efectivo siempre son bienvenidos, pero nunca obligatorios. Todo lo que te pedimos es que estés aquí con nosotros.',
  // NO NIÑOS
  tituloKids: 'NO NIÑOS',
  textoKids: 'Amamos a los niños y siempre llenan nuestras vidas de alegría. Sin embargo, en esta ocasión, hemos decidido que nuestra boda será un evento exclusivo para adultos.',
  // PASES
  tituloPases: 'PASES',
  textoPasesUno: 'Están reservados para ti',
  textoPasesDos: '2 asientos en tu honor.',
  //CONFIRMACIÓN DE ASISTENCIA
  tituloConfirmacion: 'CONFIRMA TU ASISTENCIA',
  textoConfirmacionUno: 'Por favor, confirma tu',
  textoConfirmacionDos: 'asistencia lo antes posible.',
  buttonConfirmacion: 'CONFIRMAR',
  // CONFIRMACION
  mensaje_confirmado: 'CONFIRMACIÓN DE ASISTENCIA',
  yaConfirAsistencia: '¡Ya has confirmado tu asistencia!',
  mensajeBienvenidaConfirm: 'Esperamos contar con tu presencia. Por favor confirma tu asistencia antes del ',
  cantidadAsistentes: 'El número de asientos reservados para ti es:',
  alertCantidadAsis: 'Cantidad de asistentes',
  alertaPuedesConfirmarHasta: 'Puedes confirmar hasta',
  alertaMinimoConfirmaciones: 'Debes de ingresar al menos un invitado.',
  invitNoEspecificado: 'Nos hemos dado cuenta de que no se especificaron los nombres de tus acompañantes. Te agradeceríamos mucho si pudieras proporcionarnos esta información para poder llevar un mejor control.',
  mesaAsignada: 'Tu lugar está en la mesa número:',
  NombreInvitadoInput: 'Nombre invitado',
  botonConfirmacion: 'Confirmar',
  totalInvitadosConfirmado: 'Asientos reservados:',
  despedidaEsperamosVerte: '¡Te esperamos!',
  acompañantesAgregados: 'Acompañantes Agregados:',
  txtNoAsistencia: 'Lamentamos que no puedas acompañarnos, ¡Esperamos verte muy pronto!',
  debesIngresarInvitados: 'Debes de ingresar al menos un invitado',
  puedesConfirmar: 'Puedes confirmar hasta',
  invitadoConfirmacion: 'Invitado',
  asistentesAgregados: 'Acompañantes agregados:',
  teEsperamos: '¡Te esperamos!',
  asistiras: '¿Podrás asistir?',
  siAsistire: 'Sí asistiré',
  noAsistira: 'No podre asistir',
  estasSeguro: '¿Estas seguro?',
  fechaConfirmacionCaducada: '¡Ya paso la fecha limite para confirmar tu sistencia!',
  fechaConfirmacionCaducadaDos: 'Si gustas puedes comunicarte con los novios.',
   //VENTANA EMERGENTE CONFIRMACION
   confirmAsistenciatitle: '¿Confirmas esta asistencia?',
   opcancelar: 'Cancelar',
   sininvitadostitle: '¿No agregarás invitados?',
   sininvitadostxt: 'Puedes agregar invitados si lo necesitas.',
   txtnoagregare: 'No agregaré',
   txtsiagregare: 'Si agregaré',
  // DESPEDIDA
  tituloDespedida: 'Con amor',
  DespedidaNombres: 'Litzy y Michael',
  // GLASMMY
  textoGlasmmy: 'Creado con amor por',
  glasmmy: 'GlasmmyDigital'



}
